### ISSUE TITLE
Branch Problem On The Repository

### ISSUE THREAD

**Issue by umutphp** [khadijahawa/react-native-qoute-generator#2]
The repository has two branches which are _main_ and _master_. As _main_ is the default branch and you have done all your work in _master_ branch, the [repository home page](https://github.com/khadijahawa/react-native-qoute-generator) shows an empty repository.

A careless reviewer may think you did not push your :).

**Comment by khadijahawa** [comment]
Sure I'll change it and send it back to you

Thanks for notifying me

**Comment by khadijahawa** [comment]
@umutphp I have changed the default branch to master could you please check it

**Comment by umutphp** [comment]
Great, It is ok now :).
